language: node_js
python:
- '3.3'
node_js:
- '0.11'
- '0.10'
services: mongodb
before_install:
- npm install -g bower grunt-cli
- sudo pip install Pygments
- bower install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_script:
- chmod +x ./build_scripts/groc.sh
script:
- grunt package
env:
  global:
  - GH_REF: github.com/EnoF/con-rest.git
  - MONGO_CONNECTION: mongodb://127.0.0.1:27017/test
  - secure: EVDKvMXg4/e9nNLX3FioyQxR+Gzdzs4Eii2Wg95pi9+Cx8xAi1+vd4A4NbtmmksYtSlBfXqt2MN0MwceILoq/lQSlCJImiUymn79BeJdc8n+BCz4lmxa8pn6tTrB5MNUvxzc5kWGurVtp7MonfHt+iGIFAz/dnzmLehXo1CdYPI=
addons:
  code_climate:
    repo_token: 595d5ededaf1a35799329eb35020e43cbaaa7fab05f8b53717c3a7279be0d5e0
